### ISSUE TITLE
Conflict between less package and flemay:less-autoprefixer package

### ISSUE THREAD

**Issue by ghost** [newsiberian/reaction-react#2]
Whenever I attempt to install reaction-react, I get the error: 

While determining active plugins:
   error: conflict: two packages included in the app (less and
   flemay:less-autoprefixer) are both trying to handle *.less
   error: conflict: two packages included in the app (less and
   flemay:less-autoprefixer) are both trying to handle *.lessimport

I cannot for the life of me figure out the solution, I've replaced all dependencies, removed less, added flemay:less-autoprefixer and still cannot get this working. I am trying to implement your reaction-react package. Please Advise.

**Comment by newsiberian** [comment]
Hello, this is not exactly a package, so for me it not suppose to be installed inside `reaction`, but `reaction` should be added as packages to `reaction-react`. Could you do that and comment out `less` dependencies from `package.js` in *core and maybe somewhere else. Also it is using `react-router`, so reaction iron-router references also need to be commented, at least `core/router.js`

**Comment by ghost** [comment]
Thank you, newsiberian, I've successfully managed to load and run the reaction-react package. I'll keep in touch about my progress with this great concept.

Regards, Steve.
